name: Hello World
on: 
    push: 
      
jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
        - name:  Echo text
          run:  echo MSG="Hello, world!" >> $GITHUB_ENV
        - name: use output from 
          run: echo $MSG
    job2:
        runs-on: ubuntu-latest
        steps:
        - name: use output from 
          run: echo $env.MSG
        