name: Hello World
on: 
    push: 
      
jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
        - name:  Echo text
          id: hello1
          run:  echo MSG="Hello, world!" >> $GITHUB_OUTPUT
        - name: use output from 
          run: echo $MSG
    job2:
        env:
          messages: ${{ needs.hello-job.outputs.MSG }}
        needs: hello-job
        runs-on: ubuntu-latest
        steps:
        - name: use output from 
          run: echo ${{ env.messages }}
    job3:
        runs-on: ubuntu-latest
        steps:
        - name: echo ob
          run: echo "job3" 
        